name: Build package

on: [ push, pull_request, workflow_dispatch ]

jobs:
  build_pkg:
    runs-on: ubuntu-latest
    steps:

    - name: setup docker
      uses: docker-practice/actions-setup-docker@master


    - name: install
      run: sudo apt install -y  libc6-dev-powerpc-cross gcc-powerpc64-linux-gnu gcc-powerpc-linux-gnu cpp-powerpc-linux-gnu gcc-powerpc64le-linux-gnu binutils-powerpc64-linux-gnu binutils-powerpc64le-linux-gnu binutils-powerpc-linux-gnu  bsdmainutils git python3 libglew-dev git build-essential pkg-config libusb-1.0-0-dev libsdl2-dev
    


    - name: Checkout
      uses: actions/checkout@v3

      # using pre-compiled sdk
    - name: Build PKG
      run: |
        wget -O baserom.us.z64 "https://dn790005.ca.archive.org/0/items/Nintendo64FullRegionalUploadByGhostware/Super%20Mario%2064%20%28USA%29.z64"
        docker build . -t sm64_ps3
        docker run --rm -ti -v $(pwd):/sm64 sm64_ps3 make --jobs


 




    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
          name: mario64-ps3
          path: .
          retention-days: 0
