name: C/C++ CI

on:
  push:
    branches: [ "ps3" ]
  pull_request:
    branches: [ "ps3" ]
  workflow_dispatch:

jobs:
  build-linux:
    runs-on: ubuntu-20.04
    container:
     image: debian:bullseye
    defaults:
        run:
          shell: bash
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install build dependencies
        run: ./.github/scripts/req.sh
      - name: PSL1GHT 
        run: |
         wget -q --no-check-certificate https://github.com/MiscPS3/NixSDK/releases/download/2023.09.17/bullseye-sdk.tar.gz -O psdk.tar.gz
         tar -C /usr/local/ -xzf psdk.tar.gz
         . ./.github/scripts/env.sh
        

      - name: Building 
        run: |
          wget -O baserom.us.z64 "https://dn790005.ca.archive.org/0/items/Nintendo64FullRegionalUploadByGhostware/Super%20Mario%2064%20%28USA%29.z64"
          make VERSION=us -j4 

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: mario64-ps3
          path: .
          retention-days: 0

 
