name: Build package

on: [ push, pull_request, workflow_dispatch ]

jobs:
  build_pkg:
    runs-on: ubuntu-latest
    steps:

    - name: setup docker
      uses: docker-practice/actions-setup-docker@master


    
    


    - name: Checkout
      uses: actions/checkout@v3

      # using pre-compiled sdk
    - name: Build PKG
      run: |
        git clone https://github.com/fgsfdsfgs/sm64-port.git -b ps3 --recursive
        cd sm64-port
        wget -O baserom.us.z64 "https://dn790005.ca.archive.org/0/items/Nintendo64FullRegionalUploadByGhostware/Super%20Mario%2064%20%28USA%29.z64"
        docker build . -t sm64ps3
        docker run --rm -v $(pwd):/sm64 sm64ps3 make --jobs


 




    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
          name: mario64-ps3
          path: .
          retention-days: 0
