name: C/C++ CI

on:
  push:
    branches: [ "ps3" ]
  pull_request:
    branches: [ "ps3" ]
  workflow_dispatch:

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install autoconf automake bison flex gcc libelf-dev make texinfo libncurses5-dev patch subversion wget zlib1g-dev libtool libtool-bin python2 bzip2 libgmp3-dev pkg-config g++ libssl-dev clang libelf-dev libelf++0 libelf1 build-essential pkg-config libusb-1.0-0-dev git gcc g++ gcc-multilib g++-multilib make libsdl2-dev zlib1g-dev 
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: PSL1GHT 
        run: |
         git clone https://github.com/ps3dev/ps3toolchain.git
         cd ps3toolchain
         mkdir /usr/local/ps3dev
         export PS3DEV=/usr/local/ps3dev
         export PSL1GHT=$PS3DEV

         export PATH=$PATH:$PS3DEV/bin
         export PATH=$PATH:$PS3DEV/ppu/bin
         export PATH=$PATH:$PS3DEV/spu/bin
         chmod +x toolchain.sh
         ./toolchain.sh
         git clone https://github.com/ps3dev/PSL1GHT.git
         cd PSL1GHT
         mkdir build
         export PSL1GHT=./build
         make install-ctrl
         make
         make install
         cd ..
         cd ..

        

      - name: Building 
        run: |
          wget -O baserom.us.z64 "https://dn790005.ca.archive.org/0/items/Nintendo64FullRegionalUploadByGhostware/Super%20Mario%2064%20%28USA%29.z64"
          make VERSION=us -j4 

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: mario64-ps3
          path: .
          retention-days: 0

 
